Configuration/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', HomeView.as_view(), name='home'),
    path('spp/', include('spp.urls')),
    path('petugas/', include('petugas.urls')),
    path('kelas/', include('kelas.urls')),
    path('user/', include('user.urls')),
]

spp/urls.py
from django.urls import path
from . import views

app_name = 'spp'  # nama aplkasi

urlpatterns = [
    path('', views.daftar_spp, name='daftar_spp'),
    path('tambah/', views.tambah_spp, name='tambah_spp'),
    path('spp/<int:spp_id>/', views.detail_spp, name='detail_spp'),
    path('<int:spp_id>/edit/', views.edit_spp, name='edit_spp'),
    path('<int:spp_id>/hapus/', views.hapus_spp, name='hapus_spp'),
]

spp/models.py
from django.db import models

class SPP(models.Model):
    id_spp = models.IntegerField(primary_key=True)  # id_spp sebagai primary key
    tahun = models.IntegerField()
    nominal = models.IntegerField()

spp/forms.py
from django import forms
from .models import SPP

class SPPForm(forms.ModelForm):
    class Meta:
        model = SPP
        fields = ['tahun', 'nominal']

spp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from .models import SPP
from .forms import SPPForm  # Import form yang telah dibuat

def daftar_spp(request):
    spp_list = SPP.objects.all()
    return render(request, 'spp/daftar_spp.html', {'spp_list': spp_list})

def tambah_spp(request):
    if request.method == 'POST':
        form = SPPForm(request.POST)
        if form.is_valid():
            # Mendapatkan nilai id_spp dari form atau request
            id_spp = request.POST.get('id_spp')
            tahun = form.cleaned_data['tahun']
            nominal = form.cleaned_data['nominal']
            
            # Membuat objek SPP dengan id_spp yang diberikan
            spp = SPP(id_spp=id_spp, tahun=tahun, nominal=nominal)
            spp.save()
            return HttpResponseRedirect('/spp/')
    else:
        form = SPPForm()
    
    return render(request, 'spp/tambah_spp.html', {'form': form})


def detail_spp(request, spp_id):
    spp = get_object_or_404(SPP, pk=spp_id)
    return render(request, 'spp/detail_spp.html', {'spp': spp})

def edit_spp(request, spp_id):
    spp = get_object_or_404(SPP, pk=spp_id)
    if request.method == 'POST':
        form = SPPForm(request.POST, instance=spp)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/spp/')
    else:
        form = SPPForm(instance=spp)
    
    return render(request, 'spp/edit_spp.html', {'form': form, 'spp': spp})

def hapus_spp(request, spp_id):
    spp = get_object_or_404(SPP, pk=spp_id)
    spp.delete()
    return HttpResponseRedirect('/spp/')

spp/templates/spp/daftar_spp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Daftar SPP</title>
</head>
<body>
    <h1>Daftar SPP</h1>
    <a href="{% url 'spp:tambah_spp' %}">Tambah SPP</a> <!-- Link untuk tambah SPP -->
    <table border="1">
        <thead>
            <tr>
                <th>ID</th>
                <th>Tahun</th>
                <th>Nominal</th>
                <th>Detail</th>
                <th>Edit</th>
                <th>Hapus</th>
            </tr>
        </thead>
        <tbody>
            {% for spp in spp_list %}
            <tr>
                <td>{{ spp.id_spp }}</td>
                <td>{{ spp.tahun }}</td>
                <td>{{ spp.nominal }}</td>
                <td><a href="{% url 'spp:detail_spp' spp.pk %}">Detail SPP</a></td>
                <td><a href="{% url 'spp:edit_spp' spp.pk %}">Edit</a></td>
                <td><a href="{% url 'spp:hapus_spp' spp.pk %}">Hapus</a></td>                
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

spp/templates/spp/detail_spp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail SPP</title>
</head>
<body>
    <h1>Detail SPP</h1>
    <p>ID: {{ spp.id_spp }}</p>
    <p>Tahun: {{ spp.tahun }}</p>
    <p>Nominal: {{ spp.nominal }}</p>
    <a href="{% url 'spp:edit_spp' spp.pk %}">Edit</a>
    <a href="{% url 'spp:hapus_spp' spp.pk %}">Hapus</a>
    <a href="{% url 'spp:daftar_spp' %}">Kembali ke Daftar SPP</a> <!-- Link kembali ke daftar SPP -->
</body>
</html>

spp/templates/spp/edit_spp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit SPP</title>
</head>
<body>
    <h1>Edit SPP</h1>
    <form method="post">
        {% csrf_token %}
        <label for="id_spp">ID SPP:</label>
        <span>{{ spp.id_spp }}</span><br><br>
        <label for="tahun">Tahun:</label>
        <input type="text" id="tahun" name="tahun" value="{{ spp.tahun }}"><br><br>
        <label for="nominal">Nominal:</label>
        <input type="text" id="nominal" name="nominal" value="{{ spp.nominal }}"><br><br>
        <input type="submit" value="Simpan">
    </form>
    <a href="{% url 'spp:detail_spp' spp.pk %}">Batal</a> <!-- Link untuk batal dan kembali ke detail SPP -->
</body>
</html>

spp/templates/spp/tambah_spp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tambah SPP</title>
</head>
<body>
    <h1>Tambah SPP</h1>
    <form method="post">
        {% csrf_token %}
        <label for="id_spp">ID SPP:</label>
        <input type="text" id="id_spp" name="id_spp"><br><br>
        <label for="tahun">Tahun:</label>
        <input type="text" id="tahun" name="tahun"><br><br>
        <label for="nominal">Nominal:</label>
        <input type="text" id="nominal" name="nominal"><br><br>
        <input type="submit" value="Simpan">
    </form>
    <a href="{% url 'spp:daftar_spp' %}">Kembali ke Daftar SPP</a> <!-- Link untuk kembali ke daftar SPP -->
</body>
</html>