Configuration/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', HomeView.as_view(), name='home'),
    path('spp/', include('spp.urls')),
    path('petugas/', include('petugas.urls')),
    path('kelas/', include('kelas.urls')),
    path('user/', include('user.urls')),
]

petugas/urls.py
from django.urls import path
from . import views

app_name = 'petugas'  # nama aplkasi

urlpatterns = [
    path('', views.daftar_petugas, name='daftar_petugas'),
    path('tambah/', views.tambah_petugas, name='tambah_petugas'),
    path('<int:petugas_id>/', views.detail_petugas, name='detail_petugas'),
    path('<int:petugas_id>/edit/', views.edit_petugas, name='edit_petugas'),
    path('<int:petugas_id>/hapus/', views.hapus_petugas, name='hapus_petugas'),
]

spp/urls.py
from django.urls import path
from . import views

app_name = 'spp'  # nama aplkasi

urlpatterns = [
    path('', views.daftar_spp, name='daftar_spp'),
    path('tambah/', views.tambah_spp, name='tambah_spp'),
    path('spp/<int:spp_id>/', views.detail_spp, name='detail_spp'),
    path('<int:spp_id>/edit/', views.edit_spp, name='edit_spp'),
    path('<int:spp_id>/hapus/', views.hapus_spp, name='hapus_spp'),
]

templates/home.html
<html>
<head>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">

<style>
    body {
        margin-top: 50px;
    }
    .card-body {
        min-height: 300px;
    }
</style>
</head>
<body>
<div class="container">
<br>


<div class="row justify-content-center">
<div class="col-md-6">
<div class="card">
<header class="card-header">
	<a href="{% url 'logout' %}" class="float-right btn btn-outline-primary mt-1">Log out</a>
	<h4 class="card-title mt-2">Home</h4>
</header>
<article class="card-body">
    <p class="text-center">Welcome Back {{ user.username }} !</p>
    <ul class="card-body">
        <li class="card"><a href="{% url 'petugas:daftar_petugas' %}" class="float-right btn btn-outline-primary mt-1">Petugas</a></li>
        <li class="card"><a href="{% url 'spp:daftar_spp' %}" class="float-right btn btn-outline-primary mt-1">SPP</a></li>

    </ul>
    
   
</article> <!-- card-body end .// -->
</div> <!-- card.// -->
</div> <!-- col.//-->

</div> <!-- row.//-->


</div> 
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
<!--container end.//-->
</body>
</html>